name: Dart SDK CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@6afc89df92d6eb3834022f73cd65adc8cdfcb92d # v1.8.1

      - name: Install dependencies
        run: dart pub get

      - name: Analyze
        run: dart analyze

      - name: Run tests
        run: dart test
