name: Dart SDK CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c # v1

      - name: Install dependencies
        run: dart pub get

      - name: Analyze
        run: dart analyze

      - name: Run tests
        run: dart test
